name: build-and-push-image-dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_push_image:
    uses: careerum/iaac/.github/workflows/build-and-push-image.yaml@master
    with:
      DOCKER_REGISTRY_URL: "ghcr.io/careerum/billing"
      SERVICE_NAME: billing
      SERVICE_DOCKERFILE: .docker/node/Dockerfile
      SERVICE_DOCKER_CONTEXT: .
      SERVICE_DOCKER_BUILD_ARGS: |
       TEST_NAME=${{github.sha}}
       REACT_APP_STRIPE_PUBLIC_KEY=${{secrets.REACT_APP_STRIPE_PUBLIC_KEY_DEV}}
      SERVICE_DOCKER_TARGET: "prod"
    secrets: inherit
  deploy:
    needs:
      - build_and_push_image

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Set Kubernetes Context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_FILE_OVH }}
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: get pods
      run: |
          kubectl get pods --namespace careerum-dev

    - name: Deploy Helm chart
      run: |
        helm upgrade --install billing .docker/helm -f .docker/helm/values.dev.yaml --namespace careerum-dev --set image.tag=${GITHUB_SHA::7}
